import './Form.css'

const Form = ({ setFileData, setIndexData, setSearchWords, setShowModal, setModalBody}) => {

    const submitHandler = (e) => {
        e.preventDefault();
        let searchWords = e.target[1].value;
        // let filePath = e.target[7].value;
        // hardcode filepath while developing
        const filePath = './readableFiles/autogenerated.txt';
        // const filePath = './readableFiles/test.json';
        // console.log(e.target[7].value);

        if(searchWords && filePath) {
            // when neither search option is chosen
            if(!e.target[2].checked && !e.target[3].checked) {
                // display modal
                setModalBody("Please select which search option you wish to scan the file for.")
                setShowModal(true);
                return;
            }
            // when file type isn't specified 
            if((e.target[5].checked && e.target[6].checked) || (!e.target[5].checked && !e.target[6].checked)) {
                // display modal
                setModalBody("Please choose the file type of the file to be scanned.")
                setShowModal(true);
                return;
            }

            // Search Words
            let searchText = separateSearchText(searchWords, "~");
            setSearchWords(searchText);
            console.log(`Searching for '${searchText}' in ${filePath}`);
            readFile(filePath, searchText);
            return;
        }
        // When file or searching words are not found
        // display modal
        setModalBody("Please input text to search for in the file.")
        setShowModal(true);
    }

    const separateSearchText = (text, delim) => {
        const sText = text.split(delim);
        const lower = sText.map(ele => {
            return ele.toLowerCase();
        })
        return lower;
    }

    const readFile = (file, searchTxt) => {
        console.log(`Reading .txt file...`);
        fetch(file)
        .then(res => res.text())
        .then(data => { getIndices(data.toLowerCase(), searchTxt, true)})
        .catch(err => { console.error(err) })
    }

    const getIndices = (content, searchText, isTxtFile) => {
        let index = 0;
        let iterations = 0;

        const wordArray = splitByWord(content, isTxtFile);
        let indexArray = [];
        wordArray.forEach(word => {
            searchText.forEach(searcher => {
                if(word === searcher) {
                    // console.log(`found '${searcher}' at index: ${index}`);
                    // store the index where each word is found
                    indexArray.push(index);
                }
                iterations++;
            })
            index++;
        });
        console.log(`iterations: ${iterations/index} \nwords: ${index} \nmatches: ${indexArray.length}`);
        // set index data and file data
        setFileData(wordArray);
        setIndexData(indexArray);
        return;
    }

    // replace newline and special characters from file text & split text at each space
    // removes all punctuation except the apostrophe (')
    const splitByWord = (content, isTxtFile) => {
        if(isTxtFile) {
            let fixed = content.replace(/\r?\n|\r/g, "").replace(/[.,/#!$%^&*;:{}=-_`"~()]/g, "");
            return fixed.split(" ");
        }
        return content;
    }


    return (
        <form className='fileForm' onSubmit={submitHandler}>
            <fieldset>
                <div className='form-group'>
                    <label for="textArea" className='form-label mt-4 explanation'>Enter text to search for:</label>
                    {/* <p className='text-primary disclaimer'><a className='searchMoreInfo' onClick={searchTextInfo}>More Info</a></p> */}
                    <textarea className='form-control' id='textArea' rows="2"></textarea>
                </div>
                <legend className='mt-4'>Search Options</legend>
                <p className='text-info searchDisclaimer'>Only Words Currently</p>
                <div className='form-check disabled'>
                    <label className='form-check-label'>
                        <input type="radio" className='form-check-input' name="optionsRadios" id="optionsRadios1" value="option1"/>
                        Search for Letters
                    </label>
                </div>
                <div className='form-check'>
                    <label className='form-check-label'>
                        <input type="radio" className='form-check-input' name="optionsRadios" id="optionsRadios2" value="option2" />
                        Search for Words
                    </label>
                </div>
                {/* <div className='form-check disabled'>
                    <label className='form-check-label'>
                        <input type="radio" className='form-check-input' name="optionsRadios" id="optionsRadios3" value="option3"/>
                        Search for Phrases
                    </label>
                </div> */}
                <fieldset>
                    <legend className='mt-4'>File Type</legend>
                    <p className='text-info'>Current Loaded File Type: .txt</p>
                    <div className='form-check form-switch'>
                        <label className='form-check-label' for="txtFlexSwitch">
                        <input className='form-check-input' type="checkbox" id="txtFlexSwitch" />
                        .txt
                        </label>
                    </div>
                    <div className='form-check form-switch'>
                        <label className='form-check-label' for="jsonFlexSwitch">
                        <input className='form-check-input' type="checkbox" id="jsonFlexSwitch" />
                        .json
                        </label>
                    </div>
                </fieldset>
                <div className='form-group'>
                    <legend className='mt-4'>Upload File</legend>
                    <p className='text-danger disclaimer'>Currently Cannot Read Uploaded Files</p>
                    <input className='form-control' type="file" id='formFile' accept='.txt, .json'/>
                </div>
                <div className='submissionContainer'>
                    <label for="submitBtn" className='form-label text-primary mt-4'>Submit After All Options Selected</label>
                    <br />
                </div>
                <input type="submit" className='submission' id="submitBtn" value="Scan" />
            </fieldset>
        </form>
    )
}

export default Form;